impresora:
    pattern:  /
    defaults: { _controller: "PanelBundle:Impresora:index" }

impresora_show:
    pattern:  /show/{id}
    defaults: { _controller: "PanelBundle:Impresora:show" }

impresora_new:
    pattern:  /new
    defaults: { _controller: "PanelBundle:Impresora:new" }

impresora_create:
    pattern:  /create
    defaults: { _controller: "PanelBundle:Impresora:create" }
    requirements: { _method: post }

impresora_edit:
    pattern:  /edit/{id}
    defaults: { _controller: "PanelBundle:Impresora:edit" }

impresora_update:
    pattern:  /update/{id}
    defaults: { _controller: "PanelBundle:Impresora:update" }
    requirements: { _method: post }

impresora_delete:
    pattern:  /delete/{id}
    defaults: { _controller: "PanelBundle:Impresora:delete" }