movil:
    pattern:  /
    defaults: { _controller: "PanelBundle:Movil:index" }

movil_show:
    pattern:  /show/{id}
    defaults: { _controller: "PanelBundle:Movil:show" }

movil_new:
    pattern:  /new
    defaults: { _controller: "PanelBundle:Movil:new" }

movil_create:
    pattern:  /create
    defaults: { _controller: "PanelBundle:Movil:create" }
    requirements: { _method: post }

movil_edit:
    pattern:  /edit/{id}
    defaults: { _controller: "PanelBundle:Movil:edit" }

movil_update:
    pattern:  /update/{id}
    defaults: { _controller: "PanelBundle:Movil:update" }
    requirements: { _method: post }

movil_delete:
    pattern:  /delete/{id}
    defaults: { _controller: "PanelBundle:Movil:delete" }
