ordenador:
    pattern:  /
    defaults: { _controller: "PanelBundle:Ordenador:index" }

ordenador_show:
    pattern:  /show/{id}
    defaults: { _controller: "PanelBundle:Ordenador:show" }

ordenador_new:
    pattern:  /new
    defaults: { _controller: "PanelBundle:Ordenador:new" }

ordenador_create:
    pattern:  /create
    defaults: { _controller: "PanelBundle:Ordenador:create" }
    requirements: { _method: post }

ordenador_edit:
    pattern:  /edit/{id}
    defaults: { _controller: "PanelBundle:Ordenador:edit" }

ordenador_update:
    pattern:  /update/{id}
    defaults: { _controller: "PanelBundle:Ordenador:update" }
    requirements: { _method: post }

ordenador_delete:
    pattern:  /delete/{id}
    defaults: { _controller: "PanelBundle:Ordenador:delete" }

