portada:
    pattern:  /
    defaults: { _controller: "FrontedBundle:Fronted:index" }
detail_empleado:
    pattern:  /user/{id}/detail
    defaults: { _controller: "FrontedBundle:Fronted:empleado" }
detail_ordenador:
    pattern:  /ordenador/{id}/detail
    defaults: { _controller: "FrontedBundle:Fronted:ordenador" }
detail_impresora:
    pattern:  /impresora/{id}/detail
    defaults: { _controller: "FrontedBundle:Fronted:impresora" }
detail_movil:
    pattern:  /movil/{id}/detail
    defaults: { _controller: "FrontedBundle:Fronted:movil" }