portada:
    pattern:  /
    defaults: { _controller: "FrontedBundle:Fronted:index" }

detail_empleado:
    pattern:  /user/detail/{id}
    defaults: { _controller: "FrontedBundle:Fronted:empleado" }

detail_ordenador:
    pattern:  /ordenador/detail/{id}
    defaults: { _controller: "FrontedBundle:Fronted:ordenador" }

detail_impresora:
    pattern:  /impresora/detail/{id}
    defaults: { _controller: "FrontedBundle:Fronted:impresora" }

detail_movil:
    pattern:  /movil/detail/{id}
    defaults: { _controller: "FrontedBundle:Fronted:movil" }