parameters:
#    fronted.example.class: Pasi\FrontedBundle\Example

services:
#    fronted.example:
#        class: %fronted.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
