security:

    firewalls:
        administrator:
            pattern: ^/panel
            form_login:
                login_path: login
                check_path: login_check
            logout: 
                path: /panel/logout
                target: /
                
       
        
    access_control:
        - { path: ^/panel, roles: ROLE_ADMIN }

    encoders:
        Pasi\PanelBundle\Entity\Usuario:
            algorithm: md5
            encode_as_base64: false
            iterations: 1
            
    providers:
        administrator:
            entity: {class: PanelBundle:Usuario, property: username}