<?php

namespace Pasi\OrdenadorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrdenadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenadorRepository extends EntityRepository
{
}
